#pragma once
/* Override only the constrained peripheral profile. Upstream defaults are
 * vendored verbatim and hashed; no controller or operating-system code builds. */
#define MYNEWT_VAL_BLE_ROLE_CENTRAL 0
#define MYNEWT_VAL_BLE_ROLE_OBSERVER 0
#define MYNEWT_VAL_BLE_ROLE_BROADCASTER 0
#define MYNEWT_VAL_BLE_ROLE_PERIPHERAL 1
#define MYNEWT_VAL_BLE_MAX_CONNECTIONS 1
#define MYNEWT_VAL_BLE_EXT_ADV 0
#define MYNEWT_VAL_BLE_PERIODIC_ADV 0
#define MYNEWT_VAL_BLE_SM_SC 1
#define MYNEWT_VAL_BLE_SM_SC_ONLY 1
#define MYNEWT_VAL_BLE_SM_LEGACY 0
#define MYNEWT_VAL_BLE_SM_MITM 1
#define MYNEWT_VAL_BLE_SM_BONDING 1
#define MYNEWT_VAL_BLE_SM_IO_CAP BLE_HS_IO_DISPLAY_YESNO
#define MYNEWT_VAL_BLE_SM_OUR_KEY_DIST 3
#define MYNEWT_VAL_BLE_SM_THEIR_KEY_DIST 3
#define MYNEWT_VAL_BLE_STORE_MAX_BONDS 1
#define MYNEWT_VAL_BLE_STORE_MAX_CCCDS 5
#define MYNEWT_VAL_BLE_HCI_CMD_TIMEOUT 250
#define MYNEWT_VAL_BLE_HS_STOP_ON_SHUTDOWN_TIMEOUT 250
#define MYNEWT_VAL_BLE_TRANSPORT_LL__native 0
#define MYNEWT_VAL_BLE_TRANSPORT_LL__custom 1
#define MYNEWT_VAL_BLE_TRANSPORT_EVT_COUNT 8
#define MYNEWT_VAL_BLE_TRANSPORT_EVT_SIZE 257
#define MYNEWT_VAL_BLE_TRANSPORT_EVT_DISCARDABLE_COUNT 0
#define MYNEWT_VAL_BLE_TRANSPORT_ACL_FROM_LL_COUNT 4
#define MYNEWT_VAL_BLE_TRANSPORT_ACL_FROM_HS_COUNT 4
#define MYNEWT_VAL_BLE_TRANSPORT_ACL_SIZE 251
#define MYNEWT_VAL_BLE_ATT_PREFERRED_MTU 64
#define MYNEWT_VAL_BLE_L2CAP_COC_MAX_NUM 0
#define MYNEWT_VAL_BLE_SVC_GAP_DEVICE_NAME "RiscRTE HID"
#define MYNEWT_VAL_BLE_SVC_GAP_APPEARANCE 0x03c0
#include "../../../../vendor/nimble/porting/nimble/include/syscfg/syscfg.h"
